app = "ggmarket-bot"   # Fly.io dagi bot nomi

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"

[env]

[processes]
  bot = "node bot.js"

[[services]]
  internal_port = 3000
  processes = ["bot"]
  protocol = "tcp"
  script_checks = []
